---
title: "EDA"
author: "William Donovan"
output: html_document
---

```{r}
library(tidyverse)
```

### Import weather data

```{r}
data("weather_df")
```

### Setting theme options

```{r}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r}
weather_df = weather_df |>
  mutate(month = floor_date(date, unit = "month"))
```

#### EXPLORE - MAKE A BUNCH OF PLOTS

```{r}
weather_df |>
  ggplot(aes(x = prcp)) +
  geom_histogram()
```

```{r}
weather_df |>
  filter(prcp != 0) |>
  ggplot(aes(x = prcp)) +
  geom_histogram()
```

```{r}
weather_df |>
  filter(prcp > 500) |>
  ggplot(aes(x = prcp)) +
  geom_histogram(aes(fill = name), alpha = 0.5)
```

### group_by() and summarize()

```{r}
weather_df |>
  group_by(name) |>
  summarise(
    n_obs = n())
```

```{r}
weather_df |>
  group_by(month) |>
  summarize(
    n_obs = n(),
    n_days = n_distinct(date))
```

```{r}
weather_df |>
  group_by(name, month) |>
  summarize(
    mean_tmax = mean(tmax, na.rm = TRUE),
    mean_tmin = mean(tmin, na.rm = TRUE),
    sd_prcp = sd(prcp, na.rm = TRUE))
```

### group_by and mutate()

```{r}
# Without group_by()
weather_df |>
  mutate(
    mean_tmax = mean(tmax, na.rm = TRUE))

# With group_by()
weather_df |>
  group_by(name, month) |>
  mutate(
    mean_tmax = mean(tmax, na.rm = TRUE))
```


